import 'package:marking_web/exports.dart';
import 'package:marking_web/presentation/screens/widgets_lociones.dart';

class CamisetasScreen extends StatelessWidget {
  const CamisetasScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return const Column(
      children: [
        //TODO: PRIMER ROW DE CAMISETAS
        Row(
          children: [
            Spacer(),
            WidgetCamisetas(
              imageCamiseta: 'assets/images/camisetas_1.jpg', 
              imageCamiseta2: 'assets/images/camisetas_2.jpg',
              imageWidth: 265,
              imageHeight: 370, 
              nameCamiseta: 'T-Shirt Básica',
              priceOriginal: '\$79.900',
              size: ShirtSize(size: 'XS'),
              size2: ShirtSize(size: 'S'),
              size3: ShirtSize(size: 'M'),
              size4: ShirtSize(size: 'L'),
              size5: ShirtSize(size: 'XL'),
              size6: ShirtSize(size: 'XXL'),
            ),
            Spacer(),
            WidgetCamisetas(
              imageCamiseta: 'assets/images/camisetas_1.jpg', 
              imageCamiseta2: 'assets/images/camisetas_2.jpg',
              imageWidth: 265,
              imageHeight: 370, 
              nameCamiseta: 'T-Shirt Básica',
              priceOriginal: '\$79.900',
              size: ShirtSize(size: 'XS'),
              size2: ShirtSize(size: 'S'),
              size3: ShirtSize(size: 'M'),
              size4: ShirtSize(size: 'L'),
              size5: ShirtSize(size: 'XL'),
              size6: ShirtSize(size: 'XXL'),
            ),
            Spacer(),
            WidgetCamisetas(
              imageCamiseta: 'assets/images/camisetas_1.jpg', 
              imageCamiseta2: 'assets/images/camisetas_2.jpg',
              imageWidth: 265,
              imageHeight: 370, 
              nameCamiseta: 'T-Shirt Básica',
              priceOriginal: '\$79.900',
              size: ShirtSize(size: 'XS'),
              size2: ShirtSize(size: 'S'),
              size3: ShirtSize(size: 'M'),
              size4: ShirtSize(size: 'L'),
              size5: ShirtSize(size: 'XL'),
              size6: ShirtSize(size: 'XXL'),
            ),
            Spacer(),
            WidgetCamisetas(
              imageCamiseta: 'assets/images/camisetas_1.jpg', 
              imageCamiseta2: 'assets/images/camisetas_2.jpg',
              imageWidth: 265,
              imageHeight: 370, 
              nameCamiseta: 'T-Shirt Básica',
              priceOriginal: '\$79.900',
              size: ShirtSize(size: 'XS'),
              size2: ShirtSize(size: 'S'),
              size3: ShirtSize(size: 'M'),
              size4: ShirtSize(size: 'L'),
              size5: ShirtSize(size: 'XL'),
              size6: ShirtSize(size: 'XXL'),
            ),
            Spacer(),
          ],
        ),
        SizedBox(height: 20),
        //TODO: SEGUNDO ROW DE CAMISETAS
        Row(
          children: [
            Spacer(),
            WidgetCamisetas(
              imageCamiseta: 'assets/images/camisetas_1.jpg', 
              imageCamiseta2: 'assets/images/camisetas_2.jpg',
              imageWidth: 265,
              imageHeight: 370, 
              nameCamiseta: 'T-Shirt Básica',
              priceOriginal: '\$79.900',
              size: ShirtSize(size: 'XS'),
              size2: ShirtSize(size: 'S'),
              size3: ShirtSize(size: 'M'),
              size4: ShirtSize(size: 'L'),
              size5: ShirtSize(size: 'XL'),
              size6: ShirtSize(size: 'XXL'),
            ),
            Spacer(),
            WidgetCamisetas(
              imageCamiseta: 'assets/images/camisetas_1.jpg', 
              imageCamiseta2: 'assets/images/camisetas_2.jpg',
              imageWidth: 265,
              imageHeight: 370, 
              nameCamiseta: 'T-Shirt Básica',
              priceOriginal: '\$79.900',
              size: ShirtSize(size: 'XS'),
              size2: ShirtSize(size: 'S'),
              size3: ShirtSize(size: 'M'),
              size4: ShirtSize(size: 'L'),
              size5: ShirtSize(size: 'XL'),
              size6: ShirtSize(size: 'XXL'),
            ),
            Spacer(),
            WidgetCamisetas(
              imageCamiseta: 'assets/images/camisetas_1.jpg', 
              imageCamiseta2: 'assets/images/camisetas_2.jpg',
              imageWidth: 265,
              imageHeight: 370, 
              nameCamiseta: 'T-Shirt Básica',
              priceOriginal: '\$79.900',
              size: ShirtSize(size: 'XS'),
              size2: ShirtSize(size: 'S'),
              size3: ShirtSize(size: 'M'),
              size4: ShirtSize(size: 'L'),
              size5: ShirtSize(size: 'XL'),
              size6: ShirtSize(size: 'XXL'),
            ),
            Spacer(),
            WidgetCamisetas(
              imageCamiseta: 'assets/images/camisetas_1.jpg', 
              imageCamiseta2: 'assets/images/camisetas_2.jpg',
              imageWidth: 265,
              imageHeight: 370, 
              nameCamiseta: 'T-Shirt Básica',
              priceOriginal: '\$79.900',
              size: ShirtSize(size: 'XS'),
              size2: ShirtSize(size: 'S'),
              size3: ShirtSize(size: 'M'),
              size4: ShirtSize(size: 'L'),
              size5: ShirtSize(size: 'XL'),
              size6: ShirtSize(size: 'XXL'),
            ),
            Spacer(),
          ],
        ),
        SizedBox(height: 20),
        //TODO: TERCER ROW DE CAMISETAS
        Row(
          children: [
            Spacer(),
            WidgetCamisetas(
              imageCamiseta: 'assets/images/camisetas_1.jpg', 
              imageCamiseta2: 'assets/images/camisetas_2.jpg',
              imageWidth: 265,
              imageHeight: 370, 
              nameCamiseta: 'T-Shirt Básica',
              priceOriginal: '\$79.900',
              size: ShirtSize(size: 'XS'),
              size2: ShirtSize(size: 'S'),
              size3: ShirtSize(size: 'M'),
              size4: ShirtSize(size: 'L'),
              size5: ShirtSize(size: 'XL'),
              size6: ShirtSize(size: 'XXL'),
            ),
            Spacer(),
            WidgetCamisetas(
              imageCamiseta: 'assets/images/camisetas_1.jpg', 
              imageCamiseta2: 'assets/images/camisetas_2.jpg',
              imageWidth: 265,
              imageHeight: 370, 
              nameCamiseta: 'T-Shirt Básica',
              priceOriginal: '\$79.900',
              size: ShirtSize(size: 'XS'),
              size2: ShirtSize(size: 'S'),
              size3: ShirtSize(size: 'M'),
              size4: ShirtSize(size: 'L'),
              size5: ShirtSize(size: 'XL'),
              size6: ShirtSize(size: 'XXL'),
            ),
            Spacer(),
            WidgetCamisetas(
              imageCamiseta: 'assets/images/camisetas_1.jpg', 
              imageCamiseta2: 'assets/images/camisetas_2.jpg',
              imageWidth: 265,
              imageHeight: 370, 
              nameCamiseta: 'T-Shirt Básica',
              priceOriginal: '\$79.900',
              size: ShirtSize(size: 'XS'),
              size2: ShirtSize(size: 'S'),
              size3: ShirtSize(size: 'M'),
              size4: ShirtSize(size: 'L'),
              size5: ShirtSize(size: 'XL'),
              size6: ShirtSize(size: 'XXL'),
            ),
            Spacer(),
            WidgetCamisetas(
              imageCamiseta: 'assets/images/camisetas_1.jpg', 
              imageCamiseta2: 'assets/images/camisetas_2.jpg',
              imageWidth: 265,
              imageHeight: 370, 
              nameCamiseta: 'T-Shirt Básica',
              priceOriginal: '\$79.900',
              size: ShirtSize(size: 'XS'),
              size2: ShirtSize(size: 'S'),
              size3: ShirtSize(size: 'M'),
              size4: ShirtSize(size: 'L'),
              size5: ShirtSize(size: 'XL'),
              size6: ShirtSize(size: 'XXL'),
            ),
            Spacer(),
          ],
        ),
        SizedBox(height: 20),
        //TODO: CUARTO ROW DE CAMISETAS
        Row(
          children: [
            Spacer(),
            WidgetCamisetas(
              imageCamiseta: 'assets/images/camisetas_1.jpg', 
              imageCamiseta2: 'assets/images/camisetas_2.jpg',
              imageWidth: 265,
              imageHeight: 370, 
              nameCamiseta: 'T-Shirt Básica',
              priceOriginal: '\$79.900',
              size: ShirtSize(size: 'XS'),
              size2: ShirtSize(size: 'S'),
              size3: ShirtSize(size: 'M'),
              size4: ShirtSize(size: 'L'),
              size5: ShirtSize(size: 'XL'),
              size6: ShirtSize(size: 'XXL'),
            ),
            Spacer(),
            WidgetCamisetas(
              imageCamiseta: 'assets/images/camisetas_1.jpg', 
              imageCamiseta2: 'assets/images/camisetas_2.jpg',
              imageWidth: 265,
              imageHeight: 370, 
              nameCamiseta: 'T-Shirt Básica',
              priceOriginal: '\$79.900',
              size: ShirtSize(size: 'XS'),
              size2: ShirtSize(size: 'S'),
              size3: ShirtSize(size: 'M'),
              size4: ShirtSize(size: 'L'),
              size5: ShirtSize(size: 'XL'),
              size6: ShirtSize(size: 'XXL'),
            ),
            Spacer(),
            WidgetCamisetas(
              imageCamiseta: 'assets/images/camisetas_1.jpg', 
              imageCamiseta2: 'assets/images/camisetas_2.jpg',
              imageWidth: 265,
              imageHeight: 370, 
              nameCamiseta: 'T-Shirt Básica',
              priceOriginal: '\$79.900',
              size: ShirtSize(size: 'XS'),
              size2: ShirtSize(size: 'S'),
              size3: ShirtSize(size: 'M'),
              size4: ShirtSize(size: 'L'),
              size5: ShirtSize(size: 'XL'),
              size6: ShirtSize(size: 'XXL'),
            ),
            Spacer(),
            WidgetCamisetas(
              imageCamiseta: 'assets/images/camisetas_1.jpg', 
              imageCamiseta2: 'assets/images/camisetas_2.jpg',
              imageWidth: 265,
              imageHeight: 370, 
              nameCamiseta: 'T-Shirt Básica',
              priceOriginal: '\$79.900',
              size: ShirtSize(size: 'XS'),
              size2: ShirtSize(size: 'S'),
              size3: ShirtSize(size: 'M'),
              size4: ShirtSize(size: 'L'),
              size5: ShirtSize(size: 'XL'),
              size6: ShirtSize(size: 'XXL'),
            ),
            Spacer(),
          ],
        ),
      ]
    );
  }
}