// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvaDzlorYH588EwJsHoXmujbsr631e8ak',
    appId: '1:566679008036:web:aa02dbdbd95734cc1cf9b1',
    messagingSenderId: '566679008036',
    projectId: 'aromas-selectos-web',
    authDomain: 'aromas-selectos-web.firebaseapp.com',
    storageBucket: 'aromas-selectos-web.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMUCtbUm52fQDAfcrMm95qFMbRLTKnhoc',
    appId: '1:566679008036:android:72cfbaa800349bf51cf9b1',
    messagingSenderId: '566679008036',
    projectId: 'aromas-selectos-web',
    storageBucket: 'aromas-selectos-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4T_6KSPbNLGKahy8zQ6YzjXjr7lUilQ0',
    appId: '1:566679008036:ios:1ff18f3a17522a961cf9b1',
    messagingSenderId: '566679008036',
    projectId: 'aromas-selectos-web',
    storageBucket: 'aromas-selectos-web.appspot.com',
    iosBundleId: 'com.example.markingWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4T_6KSPbNLGKahy8zQ6YzjXjr7lUilQ0',
    appId: '1:566679008036:ios:1ff18f3a17522a961cf9b1',
    messagingSenderId: '566679008036',
    projectId: 'aromas-selectos-web',
    storageBucket: 'aromas-selectos-web.appspot.com',
    iosBundleId: 'com.example.markingWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvaDzlorYH588EwJsHoXmujbsr631e8ak',
    appId: '1:566679008036:web:34d7852aeb150cbd1cf9b1',
    messagingSenderId: '566679008036',
    projectId: 'aromas-selectos-web',
    authDomain: 'aromas-selectos-web.firebaseapp.com',
    storageBucket: 'aromas-selectos-web.appspot.com',
  );
}
